    //Travel & Directions
    ["koheda", "කොහෙද", "where"],
    ["kaḍē ", "වමට හැරෙන්න", "turn left"],
    ["veediyuh", "වීදිය", "street"],
    ["issuhraha", "ඉස්සරහ", "in front"],
    ["langa", "ළඟ", "near"],
    //Verbs
    [
        ["kannuh", "කන්න", "to eat"],
        ["kanavā", "කනවා", "eating"],
        ["kævā", "කෑවා", "ate"],
        ["kannuhvā", "කන්නවා", "will eat"],
        ["kæva", "කෑව", "eaten"]
    ],
    [
        ["bonnuh", "බොන්න", "to drink"],
        ["bonuhvā", "බොනවා", "drinking"],
        ["bivvā", "බිව්වා", "drank"],
        ["bonnuhvā", "බොන්නවා", "will drink"],
        ["bivva", "බිව්ව", "drunk"]
    ],
    [
        ["yannuh", "යන්න", "to go"],
        ["yanuhvā", "යනවා", "going"],
        ["giyā", "ගියා", "went"],
        ["yannuhvā", "යන්නවා", "will go"],
        ["giya", "ගිය", "gone"]
    ],
    [
        ["ennuh", "එන්න", "to come"],
        ["enuhvā", "එනවා", "coming"],
        ["āvā", "ආවා", "came"],
        ["ennuhvā", "එන්නවා", "will come"],
        ["ā", "ආ", "come"]
    ],
    [
        ["kuhrannuh", "කරන්න", "to do"],
        ["kuhruhnuhvā", "කරනවා", "doing"],
        ["kalā", "කළා", "did"],
        ["kuhruhnnuhvā", "කරන්නවා", "will do"],
        ["kaluh", "කළ", "done"]
    ],
    [
        ["dakinnuh", "දකින්න", "to see"],
        ["dakinuhvā", "දකිනවා", "seeing"],
        ["dækkā", "දැක්කා", "saw"],
        ["dakinnuhvā", "දකින්නවා", "will see"],
        ["dækka", "දැක්ක", "seen"]
    ],
    [
        ["kiyuhwannuh", "කියවන්න", "to read"],
        ["kiyuhvuhnuhvā", "කියවනවා", "reading"],
        ["kiyevūvā", "කියෙව්වා", "read (past tense)"],
        ["kiyuhvannuhvā", "කියවන්නවා", "will read"],
        ["kiyuhvū", "කියවූ", "read (past participle)"]
    ],
    [
        ["liyannuh", "ලියන්න", "to write"],
        ["liyuhnuhvā", "ලියනවා", "writing"],
        ["livvā", "ලිව්වා", "wrote"],
        ["liyannuhvā", "ලියන්නවා", "will write"],
        ["livva", "ලිව්ව", "written"]
    ],
    [
        ["nidāgannuh", "නිදාගන්න", "to sleep"],
        ["nidāgannuhvā", "නිදාගන්නවා", "sleeping"],
        ["nidāgathtā", "නිදාගත්තා", "slept"],
        ["nidāgannuhvā", "නිදාගන්නවා", "will sleep"],
        ["nidāgath", "නිදාගත්", "slept"]
    ],
    [
        ["æhærennuh", "ඇහැරෙන්න", "to wake up"],
        ["æhærenuhvā", "ඇහැරෙනවා", "waking up"],
        ["æhærunā", "ඇහැරුණා", "woke up"],
        ["æhærennuhvā", "ඇහැරෙන්නවා", "will wake up"],
        ["æhærunuh", "ඇහැරුන", "woken up"]
    ]
    [
        ["vahannuh", "වහන්න", "to close"],
        ["vahanuhvā", "වහනවා", "closing"],
        ["vahuvā", "වහුවා", "closed"],
        ["vahannuhvā", "වහන්නවා", "will close"],
        ["vahuva", "වහුව", "closed"]
    ],
    [
        ["yavuhnnuh", "යවන්න", "to send"],
        ["yavuhnuhvā", "යවනවා", "sending"],
        ["yævvā", "යැව්වා", "sent"],
        ["yavuhnnuhvā", "යවන්නවා", "will send"],
        ["yævva", "යැව්ව", "sent"]
    ],
    [
        ["katā kuhrannuh", "කතා කරන්න", "to speak"],
        ["katā kuhruhnuhvā", "කතා කරනවා", "speaking"],
        ["katā kalā", "කතා කළා", "spoke"],
        ["katā kuhruhnnuhvā", "කතා කරන්නවා", "will speak"],
        ["katā kala", "කතා කළ", "spoken"]
    ],
    [
        ["hamu vennuh", "හමු වෙන්න", "to meet"],
        ["hamu venuhvā", "හමු වෙනවා", "meeting"],
        ["hamu vunā", "හමු වුනා", "met"],
        ["hamu vennuhvā", "හමු වෙන්නවා", "will meet"],
        ["hamu vū", "හමු වූ", "met"]
    ]
    //Unit 2
    ["ta", "ත", "ta"],
    ["ṭa", "ට", "ṭa"],
    ["i", "ි", "i"],
    ["ī", "ී", "ī"],
    ["la", "ල", "la"],
    ["ḷa", "ළ", "ḷa"],
    ["æti", "ඇති", "enough"],
    ["yaṭuh", "යට", "above"],
    //Unit 3
    ["ka", "ක", "ka"],
    ["kha", "ඛ", "kha"],
    ["e", "ෙ", "e"],
    ["ē", " ේ", "ē"],
    ["tha", "ථ", "tha"],
    ["ṭha", "ඨ", "ṭha"],
    ["kesel", "කෙසෙල්", "banana"],
    ["meya", "මෙය", "this"],
    //Unit 4
    ["ṇa", "ණ", "ṇa"],
    ["na", "න", "na"],
    ["u", "ු", "u"],
    ["ū", "ූ", "ū"],
    ["ra", "ර​", "ra"],
    ["ca", "ච", "ca"],
    ["nuguh", "නුග", "banyan"],
    ["kalu", "කලු", "black"],
    ["khu", "ඛු", "khu"],
    ["lū", "ලූ", "lū"],
    ["sē", "සේ", "sē"],
    ["khē", "ඛේ", "khē"],
    ["khū", "ඛූ", "khū"],
    ["lē", "ලේ", "lē"],
    ["sū", "සූ", "sū"],
    ["su", "සු", "su"],
    ["lu", "ලු", "lu"],
    //Unit 5
    ["va", "ව", "va"],
    ["ha", "හ", "ha"],
    ["o", "ො", "o"],
    ["ō", "ෝ", "ō"],
    ["i", "ඉ", "i"],
    ["ī", "ඊ", "ī"],
    ["hora", "හොරා", "thief"],
    ["mole", "මොලෙ", "brain"],
    ["vo", "වො", "vo"],
    ["vū", "වූ", "vū"],
    ["hū", "හූ", "hū"],
    ["vō", "වෝ", "vō"],
    ["ṇū", "ණූ", "ṇū"],
    ["ṇō", "ණෝ", "ṇō"],
    ["hō", "හෝ", "hō"],
    ["ṇo", "ණො", "ṇo"],
    ["ho", "හො", "ho"],
    //UNit 6
    ["pa", "ප", "pa"],
    ["pha", "ඵ", "pha"],
    ["v", "ව්", "v"],
    ["h", "හ්", "h"],
    ["da", "ද", "da"],
    ["dha", "ධ", "dha"],
    ["pān", "පාන්", "bread"],
    ["mal", "මල්", "flowers"],
    ["l", "ල්", "l"],
    ["k", "ක්", "k"],
    ["m", "ම්", "m"],
    ["p", "ප්", "p"],
    ["d", "ද්", "d"],
    //Unit 7
    ["ja", "ජ", "ja"],
    ["jha", "ඣ", "jha"],
    ["ai", "ෛ", "ai"],
    ["au", "ෞ", "au"],
    ["o", "ඔ", "o"],
    ["e", "එ", "e"],
    ["bauddha", "බෞද්ධ", "buddhist"],
    ["dainikuh", "දෛනික", "daily"],
    ["pau", "පෛ", "pau"],
    ["phau", "ඵෞ", "phau"],
    ["tau", "තෞ", "tau"],
    ["pai", "පෞ", "pai"],
    ["phai", "ඵෛ", "phai"],
    ["tai", "තෛ", "tai"],
    ["p", "ප්", "p"],
    ["ph", "ඵ්", "ph"],
    ["t", "ත්", "t"],
    //UNit 8
    ["gha", "ඝ", "gha"],
    ["nga", "ඞ", "nga"],
    ["ya", "්‍ය", "ya"],
    ["ra", "්‍ර", "ra"],
    ["cha", "ඡ", "cha"],
    ["fa", "ෆ​", "fa"],
    ["padhya", "පධ්‍ය", "poem"],
    ["prathuhmikuh", "ප්‍රථමික​", "primary"],
    ["jya", "ජ්‍ය", "jya"],
    ["jra", "ජ්‍ර", "jra"],
    ["jau", "ජෞ", "jau"],
    ["kya", "ක්‍ය", "kya"],
    ["kra", "ක්‍ර", "kra"],
    ["kau", "කෞ", "kau"],
    ["pya", "ප්‍ය", "pya"],
    ["pra", "ප්‍ර", "pra"],
    ["pau", "පෞ", "pau"],
    //UNit 9
    ["ña", "ඤ", "ña"],
    ["jña", "ඥ", "jña"],
    ["ung", "ං", "ung"],
    ["ḥ", "ඃ", "ḥ"],
    ["ru", "ඍ", "ru (letter)"],
    ["rū", "ඎ", "rū (letter"],
    ["sinhuhluh", "සිංහල", "sinhala"],
    ["vanuhraḥ", "වනරඃ", "wilderness"],
    ["gung", "ගං", "gung"],
    ["gaḥ", "ගඃ", "gaḥ"],
    ["gya", "ග්‍ය", "gya"],
    ["lung", "ලං", "lung"],
    ["laḥ", "ලඃ", "laḥ"],
    ["lya", "ල්‍ය", "lya"],
    ["fung", "ෆං", "fung"],
    ["faḥ", "ෆඃ", "faḥ"],
    ["fya", "ෆ්‍ර", "fya"],
    //Unit 10
    ["ḍa", "ඩ", "ḍa"],
    ["ḍha", "ඪ", "ḍha"],
    ["ræ", "රැ", "ræ"],
    ["rǣ", "රෑ", "rǣ"],
    ["ru", "රු", "ru"],
    ["rū", "රූ", "rū"],
    ["ñja", "ඦ", "ñja"],
    ["ⁿga", "ඟ", "ⁿga"],
    ["rupiyuhluh", "රුපියල", "rupees"],
    //Unit 11
    ["u", "උ", "u"],
    ["ū", "ඌ", "ū"],
    ["ru", "ෘ", "ru"],
    ["rū", "ෲ", "rū"],