export const vowels = [
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/a.png",
    correctAnswer: "a",
    answers: [
      { buttonLabel: "A", value: "a" },
      { buttonLabel: "E", value: "e" },
      { buttonLabel: "I", value: "i" },
      { buttonLabel: "U", value: "u" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/aa.png",
    correctAnswer: "aa",
    answers: [
      { buttonLabel: "AA", value: "aa" },
      { buttonLabel: "EE", value: "ee" },
      { buttonLabel: "II", value: "ii" },
      { buttonLabel: "UU", value: "uu" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/aa2.png",
    correctAnswer: "aa",
    answers: [
      { buttonLabel: "AA", value: "aa" },
      { buttonLabel: "EE", value: "ee" },
      { buttonLabel: "II", value: "ii" },
      { buttonLabel: "UU", value: "uu" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/aaa.png",
    correctAnswer: "aaa",
    answers: [
      { buttonLabel: "AAA", value: "aaa" },
      { buttonLabel: "EEE", value: "eee" },
      { buttonLabel: "III", value: "iii" },
      { buttonLabel: "UUU", value: "uuu" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/aaa2.png",
    correctAnswer: "aaa",
    answers: [
      { buttonLabel: "AAA", value: "aaa" },
      { buttonLabel: "EEE", value: "eee" },
      { buttonLabel: "III", value: "iii" },
      { buttonLabel: "UUU", value: "uuu" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ah.png",
    correctAnswer: "ah",
    answers: [
      { buttonLabel: "AH", value: "ah" },
      { buttonLabel: "EH", value: "eh" },
      { buttonLabel: "IH", value: "ih" },
      { buttonLabel: "UH", value: "uh" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ah2.png",
    correctAnswer: "ah",
    answers: [
      { buttonLabel: "AH", value: "ah" },
      { buttonLabel: "EH", value: "eh" },
      { buttonLabel: "IH", value: "ih" },
      { buttonLabel: "UH", value: "uh" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ai.png",
    correctAnswer: "ai",
    answers: [
      { buttonLabel: "AI", value: "ai" },
      { buttonLabel: "EI", value: "ei" },
      { buttonLabel: "UI", value: "ui" },
      { buttonLabel: "II", value: "ii" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ai2.png",
    correctAnswer: "ai",
    answers: [
      { buttonLabel: "AI", value: "ai" },
      { buttonLabel: "EI", value: "ei" },
      { buttonLabel: "UI", value: "ui" },
      { buttonLabel: "II", value: "ii" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/au.png",
    correctAnswer: "au",
    answers: [
      { buttonLabel: "AU", value: "au" },
      { buttonLabel: "EU", value: "eu" },
      { buttonLabel: "UU", value: "uu" },
      { buttonLabel: "IU", value: "iu" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/au2.png",
    correctAnswer: "au",
    answers: [
      { buttonLabel: "AU", value: "au" },
      { buttonLabel: "EU", value: "eu" },
      { buttonLabel: "UU", value: "uu" },
      { buttonLabel: "IU", value: "iu" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/e.png",
    correctAnswer: "e",
    answers: [
      { buttonLabel: "A", value: "a" },
      { buttonLabel: "E", value: "e" },
      { buttonLabel: "I", value: "i" },
      { buttonLabel: "U", value: "u" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/e2.png",
    correctAnswer: "e",
    answers: [
      { buttonLabel: "A", value: "a" },
      { buttonLabel: "E", value: "e" },
      { buttonLabel: "I", value: "i" },
      { buttonLabel: "U", value: "u" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ee.png",
    correctAnswer: "ee",
    answers: [
      { buttonLabel: "AA", value: "aa" },
      { buttonLabel: "EE", value: "ee" },
      { buttonLabel: "II", value: "ii" },
      { buttonLabel: "UU", value: "uu" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ee2.png",
    correctAnswer: "ee",
    answers: [
      { buttonLabel: "AA", value: "aa" },
      { buttonLabel: "EE", value: "ee" },
      { buttonLabel: "II", value: "ii" },
      { buttonLabel: "UU", value: "uu" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/i.png",
    correctAnswer: "i",
    answers: [
      { buttonLabel: "A", value: "a" },
      { buttonLabel: "E", value: "e" },
      { buttonLabel: "I", value: "i" },
      { buttonLabel: "U", value: "u" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/i2.png",
    correctAnswer: "i",
    answers: [
      { buttonLabel: "A", value: "a" },
      { buttonLabel: "E", value: "e" },
      { buttonLabel: "I", value: "i" },
      { buttonLabel: "U", value: "u" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ii.png",
    correctAnswer: "ii",
    answers: [
      { buttonLabel: "AA", value: "aa" },
      { buttonLabel: "EE", value: "ee" },
      { buttonLabel: "II", value: "ii" },
      { buttonLabel: "UU", value: "uu" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ii2.png",
    correctAnswer: "ii",
    answers: [
      { buttonLabel: "AA", value: "aa" },
      { buttonLabel: "EE", value: "ee" },
      { buttonLabel: "II", value: "ii" },
      { buttonLabel: "UU", value: "uu" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/o.png",
    correctAnswer: "o",
    answers: [
      { buttonLabel: "O", value: "o" },
      { buttonLabel: "E", value: "e" },
      { buttonLabel: "I", value: "i" },
      { buttonLabel: "U", value: "u" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/o2.png",
    correctAnswer: "o",
    answers: [
      { buttonLabel: "O", value: "o" },
      { buttonLabel: "E", value: "e" },
      { buttonLabel: "I", value: "i" },
      { buttonLabel: "U", value: "u" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/oo.png",
    correctAnswer: "oo",
    answers: [
      { buttonLabel: "OO", value: "oo" },
      { buttonLabel: "EE", value: "ee" },
      { buttonLabel: "II", value: "ii" },
      { buttonLabel: "UU", value: "uu" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/oo2.png",
    correctAnswer: "oo",
    answers: [
      { buttonLabel: "OO", value: "oo" },
      { buttonLabel: "EE", value: "ee" },
      { buttonLabel: "II", value: "ii" },
      { buttonLabel: "UU", value: "uu" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/u.png",
    correctAnswer: "u",
    answers: [
      { buttonLabel: "A", value: "a" },
      { buttonLabel: "E", value: "e" },
      { buttonLabel: "I", value: "i" },
      { buttonLabel: "U", value: "u" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/u2.png",
    correctAnswer: "u",
    answers: [
      { buttonLabel: "A", value: "a" },
      { buttonLabel: "E", value: "e" },
      { buttonLabel: "I", value: "i" },
      { buttonLabel: "U", value: "u" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/uu.png",
    correctAnswer: "uu",
    answers: [
      { buttonLabel: "AA", value: "aa" },
      { buttonLabel: "EE", value: "ee" },
      { buttonLabel: "II", value: "ii" },
      { buttonLabel: "UU", value: "uu" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/uu2.png",
    correctAnswer: "uu",
    answers: [
      { buttonLabel: "AA", value: "aa" },
      { buttonLabel: "EE", value: "ee" },
      { buttonLabel: "II", value: "ii" },
      { buttonLabel: "UU", value: "uu" },
    ],
  },
];

export const consonants = [
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ba.png",
    correctAnswer: "ba",
    answers: [
      { buttonLabel: "BA", value: "ba" },
      { buttonLabel: "BB", value: "bb" },
      { buttonLabel: "BC", value: "bc" },
      { buttonLabel: "BD", value: "bd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/bha.png",
    correctAnswer: "bha",
    answers: [
      { buttonLabel: "BHA", value: "bha" },
      { buttonLabel: "BHB", value: "bhb" },
      { buttonLabel: "BHC", value: "bhc" },
      { buttonLabel: "BHD", value: "bhd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ca.png",
    correctAnswer: "ca",
    answers: [
      { buttonLabel: "CA", value: "ca" },
      { buttonLabel: "CB", value: "cb" },
      { buttonLabel: "CC", value: "cc" },
      { buttonLabel: "CD", value: "cd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/cha.png",
    correctAnswer: "cha",
    answers: [
      { buttonLabel: "CHA", value: "cha" },
      { buttonLabel: "CHB", value: "chb" },
      { buttonLabel: "CHC", value: "chc" },
      { buttonLabel: "CHD", value: "chd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/D.a.png",
    correctAnswer: "D.a",
    answers: [
      { buttonLabel: "D.A", value: "D.a" },
      { buttonLabel: "D.B", value: "D.b" },
      { buttonLabel: "D.C", value: "D.c" },
      { buttonLabel: "D.D", value: "D.d" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/D.ha.png",
    correctAnswer: "D.ha",
    answers: [
      { buttonLabel: "D.HA", value: "D.ha" },
      { buttonLabel: "D.HB", value: "D.hb" },
      { buttonLabel: "D.HC", value: "D.hc" },
      { buttonLabel: "D.HD", value: "D.hd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/da.png",
    correctAnswer: "da",
    answers: [
      { buttonLabel: "DA", value: "da" },
      { buttonLabel: "DB", value: "db" },
      { buttonLabel: "DC", value: "dc" },
      { buttonLabel: "DD", value: "dd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/dha.png",
    correctAnswer: "dha",
    answers: [
      { buttonLabel: "DHA", value: "dha" },
      { buttonLabel: "DHB", value: "dhb" },
      { buttonLabel: "DHC", value: "dhc" },
      { buttonLabel: "DHD", value: "dhd" },
    ],
  },

  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/fa.png",
    correctAnswer: "fa",
    answers: [
      { buttonLabel: "FA", value: "fa" },
      { buttonLabel: "FB", value: "fb" },
      { buttonLabel: "FC", value: "fc" },
      { buttonLabel: "FD", value: "fd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/flag.png",
    correctAnswer: "flag1",
    answers: [
      { buttonLabel: "FLAG1", value: "flag1" },
      { buttonLabel: "FLAG2", value: "flag2" },
      { buttonLabel: "FLAG3", value: "flag3" },
      { buttonLabel: "FLAG4", value: "flag4" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ga.png",
    correctAnswer: "ga",
    answers: [
      { buttonLabel: "GA", value: "ga" },
      { buttonLabel: "GB", value: "gb" },
      { buttonLabel: "GC", value: "gc" },
      { buttonLabel: "GD", value: "gd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/gha.png",
    correctAnswer: "gha",
    answers: [
      { buttonLabel: "GHA", value: "gha" },
      { buttonLabel: "GHB", value: "ghb" },
      { buttonLabel: "GHC", value: "ghc" },
      { buttonLabel: "GHD", value: "ghd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ha.png",
    correctAnswer: "ha",
    answers: [
      { buttonLabel: "HA", value: "ha" },
      { buttonLabel: "HB", value: "hb" },
      { buttonLabel: "HC", value: "hc" },
      { buttonLabel: "HD", value: "hd" },
    ],
  },

  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/inga.png",
    correctAnswer: "inga",
    answers: [
      { buttonLabel: "INGA", value: "inga" },
      { buttonLabel: "INGB", value: "ingb" },
      { buttonLabel: "INGC", value: "ingc" },
      { buttonLabel: "INGD", value: "ingd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ja.png",
    correctAnswer: "ja",
    answers: [
      { buttonLabel: "JA", value: "ja" },
      { buttonLabel: "JB", value: "jb" },
      { buttonLabel: "JC", value: "jc" },
      { buttonLabel: "JD", value: "jd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/jha.png",
    correctAnswer: "jha",
    answers: [
      { buttonLabel: "JHA", value: "jha" },
      { buttonLabel: "JHB", value: "jhb" },
      { buttonLabel: "JHC", value: "jhc" },
      { buttonLabel: "JHD", value: "jhd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/jnna.png",
    correctAnswer: "jnna",
    answers: [
      { buttonLabel: "JNNA", value: "jnna" },
      { buttonLabel: "JNNB", value: "jnnb" },
      { buttonLabel: "JNNC", value: "jnnc" },
      { buttonLabel: "JNND", value: "jnnd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ka.png",
    correctAnswer: "ka",
    answers: [
      { buttonLabel: "KA", value: "ka" },
      { buttonLabel: "KB", value: "kb" },
      { buttonLabel: "KC", value: "kc" },
      { buttonLabel: "KD", value: "kd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/kha.png",
    correctAnswer: "kha",
    answers: [
      { buttonLabel: "KHA", value: "kha" },
      { buttonLabel: "KHB", value: "khb" },
      { buttonLabel: "KHC", value: "khc" },
      { buttonLabel: "KHD", value: "khd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/L.a.png",
    correctAnswer: "L.a",
    answers: [
      { buttonLabel: "L.A", value: "L.a" },
      { buttonLabel: "L.B", value: "L.b" },
      { buttonLabel: "L.C", value: "L.c" },
      { buttonLabel: "L.D", value: "L.d" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/la.png",
    correctAnswer: "la",
    answers: [
      { buttonLabel: "LA", value: "la" },
      { buttonLabel: "LB", value: "lb" },
      { buttonLabel: "LC", value: "lc" },
      { buttonLabel: "LD", value: "ld" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/li.png",
    correctAnswer: "li",
    answers: [
      { buttonLabel: "LI", value: "li" },
      { buttonLabel: "LJ", value: "lj" },
      { buttonLabel: "LK", value: "lk" },
      { buttonLabel: "LL", value: "ll" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/li2.png",
    correctAnswer: "li",
    answers: [
      { buttonLabel: "LI", value: "li" },
      { buttonLabel: "LJ", value: "lj" },
      { buttonLabel: "LK", value: "lk" },
      { buttonLabel: "LL", value: "ll" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/lii.png",
    correctAnswer: "lii",
    answers: [
      { buttonLabel: "LII", value: "lii" },
      { buttonLabel: "LJJ", value: "ljj" },
      { buttonLabel: "LKK", value: "lkk" },
      { buttonLabel: "LLL", value: "lll" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/lii2.png",
    correctAnswer: "lii",
    answers: [
      { buttonLabel: "LII", value: "lii" },
      { buttonLabel: "LJJ", value: "ljj" },
      { buttonLabel: "LKK", value: "lkk" },
      { buttonLabel: "LLL", value: "lll" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ma.png",
    correctAnswer: "ma",
    answers: [
      { buttonLabel: "MA", value: "ma" },
      { buttonLabel: "MB", value: "mb" },
      { buttonLabel: "MC", value: "mc" },
      { buttonLabel: "MD", value: "md" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/mba.png",
    correctAnswer: "mba",
    answers: [
      { buttonLabel: "MBA", value: "mba" },
      { buttonLabel: "MBB", value: "mbb" },
      { buttonLabel: "MBC", value: "mbc" },
      { buttonLabel: "MBD", value: "mbd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/n.a.png",
    correctAnswer: "n.a",
    answers: [
      { buttonLabel: "N.A", value: "n.a" },
      { buttonLabel: "N.B", value: "n.b" },
      { buttonLabel: "N.C", value: "n.c" },
      { buttonLabel: "N.D", value: "n.d" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/na.png",
    correctAnswer: "na",
    answers: [
      { buttonLabel: "NA", value: "na" },
      { buttonLabel: "NB", value: "nb" },
      { buttonLabel: "NC", value: "nc" },
      { buttonLabel: "ND", value: "nd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/nD.a.png",
    correctAnswer: "nD.a",
    answers: [
      { buttonLabel: "ND.A", value: "nD.a" },
      { buttonLabel: "ND.B", value: "nD.b" },
      { buttonLabel: "ND.C", value: "nD.c" },
      { buttonLabel: "ND.D", value: "nD.d" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/nda.png",
    correctAnswer: "nda",
    answers: [
      { buttonLabel: "NDA", value: "nda" },
      { buttonLabel: "NDB", value: "ndb" },
      { buttonLabel: "NDC", value: "ndc" },
      { buttonLabel: "NDD", value: "ndd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/nga.png",
    correctAnswer: "nga",
    answers: [
      { buttonLabel: "NGA", value: "nga" },
      { buttonLabel: "NGB", value: "ngb" },
      { buttonLabel: "NGC", value: "ngc" },
      { buttonLabel: "NGD", value: "ngd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/nna.png",
    correctAnswer: "nna",
    answers: [
      { buttonLabel: "NNA", value: "nna" },
      { buttonLabel: "NNB", value: "nnb" },
      { buttonLabel: "NNC", value: "nnc" },
      { buttonLabel: "NND", value: "nnd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/nnja.png",
    correctAnswer: "nnja",
    answers: [
      { buttonLabel: "NNJA", value: "nnja" },
      { buttonLabel: "NNJB", value: "nnjb" },
      { buttonLabel: "NNJC", value: "nnjc" },
      { buttonLabel: "NNJD", value: "nnjd" },
    ],
  },

  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/pa.png",
    correctAnswer: "pa",
    answers: [
      { buttonLabel: "PA", value: "pa" },
      { buttonLabel: "PB", value: "pb" },
      { buttonLabel: "PC", value: "pc" },
      { buttonLabel: "PD", value: "pd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/pha.png",
    correctAnswer: "pha",
    answers: [
      { buttonLabel: "PHA", value: "pha" },
      { buttonLabel: "PHB", value: "phb" },
      { buttonLabel: "PHC", value: "phc" },
      { buttonLabel: "PHD", value: "phd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ra.png",
    correctAnswer: "ra",
    answers: [
      { buttonLabel: "RA", value: "ra" },
      { buttonLabel: "RB", value: "rb" },
      { buttonLabel: "RC", value: "rc" },
      { buttonLabel: "RD", value: "rd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ra2.png",
    correctAnswer: "ra",
    answers: [
      { buttonLabel: "RA", value: "ra" },
      { buttonLabel: "RB", value: "rb" },
      { buttonLabel: "RC", value: "rc" },
      { buttonLabel: "RD", value: "rd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ru.png",
    correctAnswer: "ru",
    answers: [
      { buttonLabel: "RU", value: "ru" },
      { buttonLabel: "RV", value: "rv" },
      { buttonLabel: "RW", value: "rw" },
      { buttonLabel: "RX", value: "rx" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ru2.png",
    correctAnswer: "ru",
    answers: [
      { buttonLabel: "RU", value: "ru" },
      { buttonLabel: "RV", value: "rv" },
      { buttonLabel: "RW", value: "rw" },
      { buttonLabel: "RX", value: "rx" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ruu.png",
    correctAnswer: "ruu",
    answers: [
      { buttonLabel: "RUU", value: "ruu" },
      { buttonLabel: "RVV", value: "rvv" },
      { buttonLabel: "RWW", value: "rww" },
      { buttonLabel: "RXX", value: "rxx" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ruu2.png",
    correctAnswer: "ruu",
    answers: [
      { buttonLabel: "RUU", value: "ruu" },
      { buttonLabel: "RVV", value: "rvv" },
      { buttonLabel: "RWW", value: "rww" },
      { buttonLabel: "RXX", value: "rxx" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/sa.png",
    correctAnswer: "sa",
    answers: [
      { buttonLabel: "SA", value: "sa" },
      { buttonLabel: "SB", value: "sb" },
      { buttonLabel: "SC", value: "sc" },
      { buttonLabel: "SD", value: "sd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/sha.png",
    correctAnswer: "sha",
    answers: [
      { buttonLabel: "SHA", value: "sha" },
      { buttonLabel: "SHB", value: "shb" },
      { buttonLabel: "SHC", value: "shc" },
      { buttonLabel: "SHD", value: "shd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/sher.png",
    correctAnswer: "sher",
    answers: [
      { buttonLabel: "SHER", value: "sher" },
      { buttonLabel: "SHA", value: "sha" },
      { buttonLabel: "KA", value: "ka" },
      { buttonLabel: "FA", value: "fa" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/sher2.png",
    correctAnswer: "sher",
    answers: [
      { buttonLabel: "SHER", value: "sher" },
      { buttonLabel: "SHA", value: "sha" },
      { buttonLabel: "KA", value: "ka" },
      { buttonLabel: "FA", value: "fa" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/special1.png",
    correctAnswer: "special1",
    answers: [
      { buttonLabel: "SPECIAL1", value: "special1" },
      { buttonLabel: "SPECIAL2", value: "special2" },
      { buttonLabel: "SPECIAL3", value: "special3" },
      { buttonLabel: "SPECIAL4", value: "special4" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/special2.png",
    correctAnswer: "special2",
    answers: [
      { buttonLabel: "SPECIAL1", value: "special1" },
      { buttonLabel: "SPECIAL2", value: "special2" },
      { buttonLabel: "SPECIAL3", value: "special3" },
      { buttonLabel: "SPECIAL4", value: "special4" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/special3.png",
    correctAnswer: "special3",
    answers: [
      { buttonLabel: "SPECIAL1", value: "special1" },
      { buttonLabel: "SPECIAL2", value: "special2" },
      { buttonLabel: "SPECIAL3", value: "special3" },
      { buttonLabel: "SPECIAL4", value: "special4" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/T.a.png",
    correctAnswer: "T.a",
    answers: [
      { buttonLabel: "T.A", value: "T.a" },
      { buttonLabel: "T.B", value: "T.b" },
      { buttonLabel: "T.C", value: "T.c" },
      { buttonLabel: "T.D", value: "T.d" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/T.ha.png",
    correctAnswer: "T.ha",
    answers: [
      { buttonLabel: "T.HA", value: "T.ha" },
      { buttonLabel: "T.HB", value: "T.hb" },
      { buttonLabel: "T.HC", value: "T.hc" },
      { buttonLabel: "T.HD", value: "T.hd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ta.png",
    correctAnswer: "ta",
    answers: [
      { buttonLabel: "TA", value: "ta" },
      { buttonLabel: "TB", value: "tb" },
      { buttonLabel: "TC", value: "tc" },
      { buttonLabel: "TD", value: "td" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/tha.png",
    correctAnswer: "tha",
    answers: [
      { buttonLabel: "THA", value: "tha" },
      { buttonLabel: "THB", value: "thb" },
      { buttonLabel: "THC", value: "thc" },
      { buttonLabel: "THD", value: "thd" },
    ],
  },

  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/va.png",
    correctAnswer: "va",
    answers: [
      { buttonLabel: "VA", value: "va" },
      { buttonLabel: "VB", value: "vb" },
      { buttonLabel: "VC", value: "vc" },
      { buttonLabel: "VD", value: "vd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ya.png",
    correctAnswer: "ya",
    answers: [
      { buttonLabel: "YA", value: "ya" },
      { buttonLabel: "YB", value: "yb" },
      { buttonLabel: "YC", value: "yc" },
      { buttonLabel: "YD", value: "yd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ya2.png",
    correctAnswer: "ya",
    answers: [
      { buttonLabel: "YA", value: "ya" },
      { buttonLabel: "YB", value: "yb" },
      { buttonLabel: "YC", value: "yc" },
      { buttonLabel: "YD", value: "yd" },
    ],
  },
];
