export const vowels = [
  {
    question: "What is this letter?",
    phonetic: "අ",
    correctAnswer: "a",
    answers: [
      { buttonLabel: "a", value: "a" },
      { buttonLabel: "e", value: "e" },
      { buttonLabel: "i", value: "i" },
      { buttonLabel: "u", value: "u" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ආ",
    correctAnswer: "ā",
    answers: [
      { buttonLabel: "ā", value: "ā" },
      { buttonLabel: "ē", value: "ē" },
      { buttonLabel: "ī", value: "ī" },
      { buttonLabel: "ū", value: "ū" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ා ",
    correctAnswer: "ā",
    answers: [
      { buttonLabel: "ā", value: "ā" },
      { buttonLabel: "ē", value: "ē" },
      { buttonLabel: "ī", value: "ī" },
      { buttonLabel: "ū", value: "ū" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ඇ",
    correctAnswer: "æ",
    answers: [
      { buttonLabel: "æ", value: "æ" },
      { buttonLabel: "ē", value: "ē" },
      { buttonLabel: "ī", value: "ī" },
      { buttonLabel: "ai", value: "ai" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ැ",
    correctAnswer: "æ",
    answers: [
      { buttonLabel: "æ", value: "æ" },
      { buttonLabel: "ē", value: "ē" },
      { buttonLabel: "ī", value: "ī" },
      { buttonLabel: "ai", value: "ai" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ඈ",
    correctAnswer: "ǣ",
    answers: [
      { buttonLabel: "ǣ", value: "ǣ" },
      { buttonLabel: "ē", value: "ē" },
      { buttonLabel: "ū", value: "ū" },
      { buttonLabel: "ai", value: "ai" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ෑ",
    correctAnswer: "ǣ",
    answers: [
      { buttonLabel: "ǣ", value: "ǣ" },
      { buttonLabel: "ē", value: "ē" },
      { buttonLabel: "ū", value: "ū" },
      { buttonLabel: "ai", value: "ai" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ඓ",
    correctAnswer: "ai",
    answers: [
      { buttonLabel: "ai", value: "ai" },
      { buttonLabel: "ē", value: "ē" },
      { buttonLabel: "ū", value: "ū" },
      { buttonLabel: "ǣ", value: "ǣ" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ෛ",
    correctAnswer: "ai",
    answers: [
      { buttonLabel: "ai", value: "ai" },
      { buttonLabel: "ē", value: "ē" },
      { buttonLabel: "ū", value: "ū" },
      { buttonLabel: "ǣ", value: "ǣ" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ඖ",
    correctAnswer: "au",
    answers: [
      { buttonLabel: "au", value: "au" },
      { buttonLabel: "ai", value: "ai" },
      { buttonLabel: "ū", value: "ū" },
      { buttonLabel: "ǣ", value: "ǣ" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ෞ",
    correctAnswer: "au",
    answers: [
      { buttonLabel: "au", value: "au" },
      { buttonLabel: "ai", value: "ai" },
      { buttonLabel: "ū", value: "ū" },
      { buttonLabel: "ǣ", value: "ǣ" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "එ",
    correctAnswer: "e",
    answers: [
      { buttonLabel: "a", value: "a" },
      { buttonLabel: "e", value: "e" },
      { buttonLabel: "i", value: "i" },
      { buttonLabel: "u", value: "u" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ෙ",
    correctAnswer: "e",
    answers: [
      { buttonLabel: "a", value: "a" },
      { buttonLabel: "e", value: "e" },
      { buttonLabel: "i", value: "i" },
      { buttonLabel: "u", value: "u" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ඒ",
    correctAnswer: "ē",
    answers: [
      { buttonLabel: "ā", value: "ā" },
      { buttonLabel: "ē", value: "ē" },
      { buttonLabel: "ī", value: "ī" },
      { buttonLabel: "ū", value: "ū" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ේ",
    correctAnswer: "ē",
    answers: [
      { buttonLabel: "ā", value: "ā" },
      { buttonLabel: "ē", value: "ē" },
      { buttonLabel: "ī", value: "ī" },
      { buttonLabel: "ū", value: "ū" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ඉ",
    correctAnswer: "i",
    answers: [
      { buttonLabel: "a", value: "a" },
      { buttonLabel: "e", value: "e" },
      { buttonLabel: "i", value: "i" },
      { buttonLabel: "u", value: "u" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ි",
    correctAnswer: "i",
    answers: [
      { buttonLabel: "a", value: "a" },
      { buttonLabel: "e", value: "e" },
      { buttonLabel: "i", value: "i" },
      { buttonLabel: "u", value: "u" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ඊ",
    correctAnswer: "ī",
    answers: [
      { buttonLabel: "ā", value: "ā" },
      { buttonLabel: "ē", value: "ē" },
      { buttonLabel: "ī", value: "ī" },
      { buttonLabel: "ū", value: "ū" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ී",
    correctAnswer: "ī",
    answers: [
      { buttonLabel: "ā", value: "ā" },
      { buttonLabel: "ē", value: "ē" },
      { buttonLabel: "ī", value: "ī" },
      { buttonLabel: "ū", value: "ū" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ඔ",
    correctAnswer: "o",
    answers: [
      { buttonLabel: "a", value: "a" },
      { buttonLabel: "e", value: "e" },
      { buttonLabel: "o", value: "o" },
      { buttonLabel: "u", value: "u" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ො",
    correctAnswer: "o",
    answers: [
      { buttonLabel: "a", value: "a" },
      { buttonLabel: "e", value: "e" },
      { buttonLabel: "o", value: "o" },
      { buttonLabel: "u", value: "u" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ඕ",
    correctAnswer: "ō",
    answers: [
      { buttonLabel: "ā", value: "ā" },
      { buttonLabel: "ē", value: "ē" },
      { buttonLabel: "ō", value: "ō" },
      { buttonLabel: "ū", value: "ū" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ෝ",
    correctAnswer: "ō",
    answers: [
      { buttonLabel: "ā", value: "ā" },
      { buttonLabel: "ē", value: "ē" },
      { buttonLabel: "ō", value: "ō" },
      { buttonLabel: "ū", value: "ū" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "උ",
    correctAnswer: "u",
    answers: [
      { buttonLabel: "a", value: "a" },
      { buttonLabel: "e", value: "e" },
      { buttonLabel: "o", value: "o" },
      { buttonLabel: "u", value: "u" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ු",
    correctAnswer: "u",
    answers: [
      { buttonLabel: "a", value: "a" },
      { buttonLabel: "e", value: "e" },
      { buttonLabel: "o", value: "o" },
      { buttonLabel: "u", value: "u" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ඌ",
    correctAnswer: "ū",
    answers: [
      { buttonLabel: "ā", value: "ā" },
      { buttonLabel: "ē", value: "ē" },
      { buttonLabel: "ō", value: "ō" },
      { buttonLabel: "ū", value: "ū" },
    ],
  },
  {
    question: "What is this letter?",
    phonetic: "ූ",
    correctAnswer: "ū",
    answers: [
      { buttonLabel: "ā", value: "ā" },
      { buttonLabel: "ē", value: "ē" },
      { buttonLabel: "ō", value: "ō" },
      { buttonLabel: "ū", value: "ū" },
    ],
  },
];

export const consonants = [
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ba.png",
    correctAnswer: "ba",
    answers: [
      { buttonLabel: "BA", value: "ba" },
      { buttonLabel: "BB", value: "bb" },
      { buttonLabel: "BC", value: "bc" },
      { buttonLabel: "BD", value: "bd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/bha.png",
    correctAnswer: "bha",
    answers: [
      { buttonLabel: "BHA", value: "bha" },
      { buttonLabel: "BHB", value: "bhb" },
      { buttonLabel: "BHC", value: "bhc" },
      { buttonLabel: "BHD", value: "bhd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ca.png",
    correctAnswer: "ca",
    answers: [
      { buttonLabel: "CA", value: "ca" },
      { buttonLabel: "CB", value: "cb" },
      { buttonLabel: "CC", value: "cc" },
      { buttonLabel: "CD", value: "cd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/cha.png",
    correctAnswer: "cha",
    answers: [
      { buttonLabel: "CHA", value: "cha" },
      { buttonLabel: "CHB", value: "chb" },
      { buttonLabel: "CHC", value: "chc" },
      { buttonLabel: "CHD", value: "chd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/D.a.png",
    correctAnswer: "D.a",
    answers: [
      { buttonLabel: "D.A", value: "D.a" },
      { buttonLabel: "D.B", value: "D.b" },
      { buttonLabel: "D.C", value: "D.c" },
      { buttonLabel: "D.D", value: "D.d" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/D.ha.png",
    correctAnswer: "D.ha",
    answers: [
      { buttonLabel: "D.HA", value: "D.ha" },
      { buttonLabel: "D.HB", value: "D.hb" },
      { buttonLabel: "D.HC", value: "D.hc" },
      { buttonLabel: "D.HD", value: "D.hd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/da.png",
    correctAnswer: "da",
    answers: [
      { buttonLabel: "DA", value: "da" },
      { buttonLabel: "DB", value: "db" },
      { buttonLabel: "DC", value: "dc" },
      { buttonLabel: "DD", value: "dd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/dha.png",
    correctAnswer: "dha",
    answers: [
      { buttonLabel: "DHA", value: "dha" },
      { buttonLabel: "DHB", value: "dhb" },
      { buttonLabel: "DHC", value: "dhc" },
      { buttonLabel: "DHD", value: "dhd" },
    ],
  },

  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/fa.png",
    correctAnswer: "fa",
    answers: [
      { buttonLabel: "FA", value: "fa" },
      { buttonLabel: "FB", value: "fb" },
      { buttonLabel: "FC", value: "fc" },
      { buttonLabel: "FD", value: "fd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/flag.png",
    correctAnswer: "flag1",
    answers: [
      { buttonLabel: "FLAG1", value: "flag1" },
      { buttonLabel: "FLAG2", value: "flag2" },
      { buttonLabel: "FLAG3", value: "flag3" },
      { buttonLabel: "FLAG4", value: "flag4" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ga.png",
    correctAnswer: "ga",
    answers: [
      { buttonLabel: "GA", value: "ga" },
      { buttonLabel: "GB", value: "gb" },
      { buttonLabel: "GC", value: "gc" },
      { buttonLabel: "GD", value: "gd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/gha.png",
    correctAnswer: "gha",
    answers: [
      { buttonLabel: "GHA", value: "gha" },
      { buttonLabel: "GHB", value: "ghb" },
      { buttonLabel: "GHC", value: "ghc" },
      { buttonLabel: "GHD", value: "ghd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ha.png",
    correctAnswer: "ha",
    answers: [
      { buttonLabel: "HA", value: "ha" },
      { buttonLabel: "HB", value: "hb" },
      { buttonLabel: "HC", value: "hc" },
      { buttonLabel: "HD", value: "hd" },
    ],
  },

  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/inga.png",
    correctAnswer: "inga",
    answers: [
      { buttonLabel: "INGA", value: "inga" },
      { buttonLabel: "INGB", value: "ingb" },
      { buttonLabel: "INGC", value: "ingc" },
      { buttonLabel: "INGD", value: "ingd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ja.png",
    correctAnswer: "ja",
    answers: [
      { buttonLabel: "JA", value: "ja" },
      { buttonLabel: "JB", value: "jb" },
      { buttonLabel: "JC", value: "jc" },
      { buttonLabel: "JD", value: "jd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/jha.png",
    correctAnswer: "jha",
    answers: [
      { buttonLabel: "JHA", value: "jha" },
      { buttonLabel: "JHB", value: "jhb" },
      { buttonLabel: "JHC", value: "jhc" },
      { buttonLabel: "JHD", value: "jhd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/jnna.png",
    correctAnswer: "jnna",
    answers: [
      { buttonLabel: "JNNA", value: "jnna" },
      { buttonLabel: "JNNB", value: "jnnb" },
      { buttonLabel: "JNNC", value: "jnnc" },
      { buttonLabel: "JNND", value: "jnnd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ka.png",
    correctAnswer: "ka",
    answers: [
      { buttonLabel: "KA", value: "ka" },
      { buttonLabel: "KB", value: "kb" },
      { buttonLabel: "KC", value: "kc" },
      { buttonLabel: "KD", value: "kd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/kha.png",
    correctAnswer: "kha",
    answers: [
      { buttonLabel: "KHA", value: "kha" },
      { buttonLabel: "KHB", value: "khb" },
      { buttonLabel: "KHC", value: "khc" },
      { buttonLabel: "KHD", value: "khd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/L.a.png",
    correctAnswer: "L.a",
    answers: [
      { buttonLabel: "L.A", value: "L.a" },
      { buttonLabel: "L.B", value: "L.b" },
      { buttonLabel: "L.C", value: "L.c" },
      { buttonLabel: "L.D", value: "L.d" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/la.png",
    correctAnswer: "la",
    answers: [
      { buttonLabel: "LA", value: "la" },
      { buttonLabel: "LB", value: "lb" },
      { buttonLabel: "LC", value: "lc" },
      { buttonLabel: "LD", value: "ld" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/li.png",
    correctAnswer: "li",
    answers: [
      { buttonLabel: "LI", value: "li" },
      { buttonLabel: "LJ", value: "lj" },
      { buttonLabel: "LK", value: "lk" },
      { buttonLabel: "LL", value: "ll" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/li2.png",
    correctAnswer: "li",
    answers: [
      { buttonLabel: "LI", value: "li" },
      { buttonLabel: "LJ", value: "lj" },
      { buttonLabel: "LK", value: "lk" },
      { buttonLabel: "LL", value: "ll" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/lii.png",
    correctAnswer: "lii",
    answers: [
      { buttonLabel: "LII", value: "lii" },
      { buttonLabel: "LJJ", value: "ljj" },
      { buttonLabel: "LKK", value: "lkk" },
      { buttonLabel: "LLL", value: "lll" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/lii2.png",
    correctAnswer: "lii",
    answers: [
      { buttonLabel: "LII", value: "lii" },
      { buttonLabel: "LJJ", value: "ljj" },
      { buttonLabel: "LKK", value: "lkk" },
      { buttonLabel: "LLL", value: "lll" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ma.png",
    correctAnswer: "ma",
    answers: [
      { buttonLabel: "MA", value: "ma" },
      { buttonLabel: "MB", value: "mb" },
      { buttonLabel: "MC", value: "mc" },
      { buttonLabel: "MD", value: "md" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/mba.png",
    correctAnswer: "mba",
    answers: [
      { buttonLabel: "MBA", value: "mba" },
      { buttonLabel: "MBB", value: "mbb" },
      { buttonLabel: "MBC", value: "mbc" },
      { buttonLabel: "MBD", value: "mbd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/n.a.png",
    correctAnswer: "n.a",
    answers: [
      { buttonLabel: "N.A", value: "n.a" },
      { buttonLabel: "N.B", value: "n.b" },
      { buttonLabel: "N.C", value: "n.c" },
      { buttonLabel: "N.D", value: "n.d" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/na.png",
    correctAnswer: "na",
    answers: [
      { buttonLabel: "NA", value: "na" },
      { buttonLabel: "NB", value: "nb" },
      { buttonLabel: "NC", value: "nc" },
      { buttonLabel: "ND", value: "nd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/nD.a.png",
    correctAnswer: "nD.a",
    answers: [
      { buttonLabel: "ND.A", value: "nD.a" },
      { buttonLabel: "ND.B", value: "nD.b" },
      { buttonLabel: "ND.C", value: "nD.c" },
      { buttonLabel: "ND.D", value: "nD.d" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/nda.png",
    correctAnswer: "nda",
    answers: [
      { buttonLabel: "NDA", value: "nda" },
      { buttonLabel: "NDB", value: "ndb" },
      { buttonLabel: "NDC", value: "ndc" },
      { buttonLabel: "NDD", value: "ndd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/nga.png",
    correctAnswer: "nga",
    answers: [
      { buttonLabel: "NGA", value: "nga" },
      { buttonLabel: "NGB", value: "ngb" },
      { buttonLabel: "NGC", value: "ngc" },
      { buttonLabel: "NGD", value: "ngd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/nna.png",
    correctAnswer: "nna",
    answers: [
      { buttonLabel: "NNA", value: "nna" },
      { buttonLabel: "NNB", value: "nnb" },
      { buttonLabel: "NNC", value: "nnc" },
      { buttonLabel: "NND", value: "nnd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/nnja.png",
    correctAnswer: "nnja",
    answers: [
      { buttonLabel: "NNJA", value: "nnja" },
      { buttonLabel: "NNJB", value: "nnjb" },
      { buttonLabel: "NNJC", value: "nnjc" },
      { buttonLabel: "NNJD", value: "nnjd" },
    ],
  },

  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/pa.png",
    correctAnswer: "pa",
    answers: [
      { buttonLabel: "PA", value: "pa" },
      { buttonLabel: "PB", value: "pb" },
      { buttonLabel: "PC", value: "pc" },
      { buttonLabel: "PD", value: "pd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/pha.png",
    correctAnswer: "pha",
    answers: [
      { buttonLabel: "PHA", value: "pha" },
      { buttonLabel: "PHB", value: "phb" },
      { buttonLabel: "PHC", value: "phc" },
      { buttonLabel: "PHD", value: "phd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ra.png",
    correctAnswer: "ra",
    answers: [
      { buttonLabel: "RA", value: "ra" },
      { buttonLabel: "RB", value: "rb" },
      { buttonLabel: "RC", value: "rc" },
      { buttonLabel: "RD", value: "rd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ra2.png",
    correctAnswer: "ra",
    answers: [
      { buttonLabel: "RA", value: "ra" },
      { buttonLabel: "RB", value: "rb" },
      { buttonLabel: "RC", value: "rc" },
      { buttonLabel: "RD", value: "rd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ru.png",
    correctAnswer: "ru",
    answers: [
      { buttonLabel: "RU", value: "ru" },
      { buttonLabel: "RV", value: "rv" },
      { buttonLabel: "RW", value: "rw" },
      { buttonLabel: "RX", value: "rx" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ru2.png",
    correctAnswer: "ru",
    answers: [
      { buttonLabel: "RU", value: "ru" },
      { buttonLabel: "RV", value: "rv" },
      { buttonLabel: "RW", value: "rw" },
      { buttonLabel: "RX", value: "rx" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ruu.png",
    correctAnswer: "ruu",
    answers: [
      { buttonLabel: "RUU", value: "ruu" },
      { buttonLabel: "RVV", value: "rvv" },
      { buttonLabel: "RWW", value: "rww" },
      { buttonLabel: "RXX", value: "rxx" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ruu2.png",
    correctAnswer: "ruu",
    answers: [
      { buttonLabel: "RUU", value: "ruu" },
      { buttonLabel: "RVV", value: "rvv" },
      { buttonLabel: "RWW", value: "rww" },
      { buttonLabel: "RXX", value: "rxx" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/sa.png",
    correctAnswer: "sa",
    answers: [
      { buttonLabel: "SA", value: "sa" },
      { buttonLabel: "SB", value: "sb" },
      { buttonLabel: "SC", value: "sc" },
      { buttonLabel: "SD", value: "sd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/sha.png",
    correctAnswer: "sha",
    answers: [
      { buttonLabel: "SHA", value: "sha" },
      { buttonLabel: "SHB", value: "shb" },
      { buttonLabel: "SHC", value: "shc" },
      { buttonLabel: "SHD", value: "shd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/sher.png",
    correctAnswer: "sher",
    answers: [
      { buttonLabel: "SHER", value: "sher" },
      { buttonLabel: "SHA", value: "sha" },
      { buttonLabel: "KA", value: "ka" },
      { buttonLabel: "FA", value: "fa" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/sher2.png",
    correctAnswer: "sher",
    answers: [
      { buttonLabel: "SHER", value: "sher" },
      { buttonLabel: "SHA", value: "sha" },
      { buttonLabel: "KA", value: "ka" },
      { buttonLabel: "FA", value: "fa" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/special1.png",
    correctAnswer: "special1",
    answers: [
      { buttonLabel: "SPECIAL1", value: "special1" },
      { buttonLabel: "SPECIAL2", value: "special2" },
      { buttonLabel: "SPECIAL3", value: "special3" },
      { buttonLabel: "SPECIAL4", value: "special4" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/special2.png",
    correctAnswer: "special2",
    answers: [
      { buttonLabel: "SPECIAL1", value: "special1" },
      { buttonLabel: "SPECIAL2", value: "special2" },
      { buttonLabel: "SPECIAL3", value: "special3" },
      { buttonLabel: "SPECIAL4", value: "special4" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/special3.png",
    correctAnswer: "special3",
    answers: [
      { buttonLabel: "SPECIAL1", value: "special1" },
      { buttonLabel: "SPECIAL2", value: "special2" },
      { buttonLabel: "SPECIAL3", value: "special3" },
      { buttonLabel: "SPECIAL4", value: "special4" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/T.a.png",
    correctAnswer: "T.a",
    answers: [
      { buttonLabel: "T.A", value: "T.a" },
      { buttonLabel: "T.B", value: "T.b" },
      { buttonLabel: "T.C", value: "T.c" },
      { buttonLabel: "T.D", value: "T.d" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/T.ha.png",
    correctAnswer: "T.ha",
    answers: [
      { buttonLabel: "T.HA", value: "T.ha" },
      { buttonLabel: "T.HB", value: "T.hb" },
      { buttonLabel: "T.HC", value: "T.hc" },
      { buttonLabel: "T.HD", value: "T.hd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ta.png",
    correctAnswer: "ta",
    answers: [
      { buttonLabel: "TA", value: "ta" },
      { buttonLabel: "TB", value: "tb" },
      { buttonLabel: "TC", value: "tc" },
      { buttonLabel: "TD", value: "td" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/tha.png",
    correctAnswer: "tha",
    answers: [
      { buttonLabel: "THA", value: "tha" },
      { buttonLabel: "THB", value: "thb" },
      { buttonLabel: "THC", value: "thc" },
      { buttonLabel: "THD", value: "thd" },
    ],
  },

  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/va.png",
    correctAnswer: "va",
    answers: [
      { buttonLabel: "VA", value: "va" },
      { buttonLabel: "VB", value: "vb" },
      { buttonLabel: "VC", value: "vc" },
      { buttonLabel: "VD", value: "vd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ya.png",
    correctAnswer: "ya",
    answers: [
      { buttonLabel: "YA", value: "ya" },
      { buttonLabel: "YB", value: "yb" },
      { buttonLabel: "YC", value: "yc" },
      { buttonLabel: "YD", value: "yd" },
    ],
  },
  {
    question: "What is this letter?",
    imagePath: "/sinhalaLetters/ya2.png",
    correctAnswer: "ya",
    answers: [
      { buttonLabel: "YA", value: "ya" },
      { buttonLabel: "YB", value: "yb" },
      { buttonLabel: "YC", value: "yc" },
      { buttonLabel: "YD", value: "yd" },
    ],
  },
];

export const numbers = [
  [
    {
      question: "What is this number?",
      phonetic: "0",
      correctAnswer: "zero",
      answers: [
        { buttonLabel: "tuna", value: "three", sinhala: "තුන" },
        { buttonLabel: "deka", value: "two", sinhala: "දෙක" },
        { buttonLabel: "eka", value: "one", sinhala: "එක" },
        { buttonLabel: "binduva", value: "zero", sinhala: "බින්දුව" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "බින්දුව",
      correctAnswer: "0",
      answers: [
        { buttonLabel: "0", value: "0" },
        { buttonLabel: "1", value: "1" },
        { buttonLabel: "4", value: "4" },
        { buttonLabel: "7", value: "7" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "1",
      correctAnswer: "one",
      answers: [
        { buttonLabel: "tuna", value: "three", sinhala: "තුන" },
        { buttonLabel: "deka", value: "two", sinhala: "දෙක" },
        { buttonLabel: "eka", value: "one", sinhala: "එක" },
        { buttonLabel: "binduva", value: "zero", sinhala: "බින්දුව" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "එක",
      correctAnswer: "1",
      answers: [
        { buttonLabel: "0", value: "0" },
        { buttonLabel: "1", value: "1" },
        { buttonLabel: "4", value: "4" },
        { buttonLabel: "7", value: "7" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "2",
      correctAnswer: "two",
      answers: [
        { buttonLabel: "tuna", value: "three", sinhala: "තුන" },
        { buttonLabel: "deka", value: "two", sinhala: "දෙක" },
        { buttonLabel: "eka", value: "one", sinhala: "එක" },
        { buttonLabel: "binduva", value: "zero", sinhala: "බින්දුව" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "දෙක",
      correctAnswer: "2",
      answers: [
        { buttonLabel: "2", value: "2" },
        { buttonLabel: "3", value: "3" },
        { buttonLabel: "5", value: "5" },
        { buttonLabel: "8", value: "8" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "3",
      correctAnswer: "three",
      answers: [
        { buttonLabel: "tuna", value: "three", sinhala: "තුන" },
        { buttonLabel: "haya", value: "six", sinhala: "හ‍ය" },
        { buttonLabel: "paha", value: "five", sinhala: "පහ" },
        { buttonLabel: "hatara", value: "four", sinhala: "හතර" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "තුන",
      correctAnswer: "3",
      answers: [
        { buttonLabel: "2", value: "2" },
        { buttonLabel: "3", value: "3" },
        { buttonLabel: "5", value: "5" },
        { buttonLabel: "8", value: "8" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "4",
      correctAnswer: "four",
      answers: [
        { buttonLabel: "tuna", value: "three", sinhala: "තුන" },
        { buttonLabel: "haya", value: "six", sinhala: "හ‍ය" },
        { buttonLabel: "paha", value: "five", sinhala: "පහ" },
        { buttonLabel: "hatara", value: "four", sinhala: "හතර" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "හතර",
      correctAnswer: "4",
      answers: [
        { buttonLabel: "4", value: "4" },
        { buttonLabel: "3", value: "3" },
        { buttonLabel: "5", value: "5" },
        { buttonLabel: "8", value: "8" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "5",
      correctAnswer: "five",
      answers: [
        { buttonLabel: "tuna", value: "three", sinhala: "තුන" },
        { buttonLabel: "haya", value: "six", sinhala: "හ‍ය" },
        { buttonLabel: "paha", value: "five", sinhala: "පහ" },
        { buttonLabel: "hatara", value: "four", sinhala: "හතර" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "පහ",
      correctAnswer: "5",
      answers: [
        { buttonLabel: "9", value: "9" },
        { buttonLabel: "3", value: "3" },
        { buttonLabel: "5", value: "5" },
        { buttonLabel: "8", value: "8" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "6",
      correctAnswer: "six",
      answers: [
        { buttonLabel: "tuna", value: "three", sinhala: "තුන" },
        { buttonLabel: "haya", value: "six", sinhala: "හ‍ය" },
        { buttonLabel: "paha", value: "five", sinhala: "පහ" },
        { buttonLabel: "hatara", value: "four", sinhala: "හතර" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "හ‍ය",
      correctAnswer: "6",
      answers: [
        { buttonLabel: "9", value: "9" },
        { buttonLabel: "6", value: "6" },
        { buttonLabel: "5", value: "5" },
        { buttonLabel: "8", value: "8" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "7",
      correctAnswer: "seven",
      answers: [
        { buttonLabel: "namaya", value: "nine", sinhala: "නම‍ය" },
        { buttonLabel: "hata", value: "seven", sinhala: "හත" },
        { buttonLabel: "dahaya", value: "ten", sinhala: "දහ‍ය" },
        { buttonLabel: "aṭa", value: "eight", sinhala: "අට" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "හත",
      correctAnswer: "7",
      answers: [
        { buttonLabel: "9", value: "9" },
        { buttonLabel: "7", value: "7" },
        { buttonLabel: "5", value: "5" },
        { buttonLabel: "8", value: "8" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "8",
      correctAnswer: "eight",
      answers: [
        { buttonLabel: "namaya", value: "nine", sinhala: "නම‍ය" },
        { buttonLabel: "hata", value: "seven", sinhala: "හත" },
        { buttonLabel: "dahaya", value: "ten", sinhala: "දහ‍ය" },
        { buttonLabel: "aṭa", value: "eight", sinhala: "අට" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "අට",
      correctAnswer: "8",
      answers: [
        { buttonLabel: "9", value: "9" },
        { buttonLabel: "7", value: "7" },
        { buttonLabel: "5", value: "5" },
        { buttonLabel: "8", value: "8" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "9",
      correctAnswer: "nine",
      answers: [
        { buttonLabel: "namaya", value: "nine", sinhala: "නම‍ය" },
        { buttonLabel: "hata", value: "seven", sinhala: "හත" },
        { buttonLabel: "dahaya", value: "ten", sinhala: "දහ‍ය" },
        { buttonLabel: "aṭa", value: "eight", sinhala: "අට" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "නම‍ය",
      correctAnswer: "9",
      answers: [
        { buttonLabel: "9", value: "9" },
        { buttonLabel: "7", value: "7" },
        { buttonLabel: "10", value: "10" },
        { buttonLabel: "8", value: "8" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "10",
      correctAnswer: "ten",
      answers: [
        { buttonLabel: "namaya", value: "nine", sinhala: "නම‍ය" },
        { buttonLabel: "hata", value: "seven", sinhala: "හත" },
        { buttonLabel: "dahaya", value: "ten", sinhala: "දහ‍ය" },
        { buttonLabel: "aṭa", value: "eight", sinhala: "අට" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "දහ‍ය",
      correctAnswer: "10",
      answers: [
        { buttonLabel: "9", value: "9" },
        { buttonLabel: "7", value: "7" },
        { buttonLabel: "10", value: "10" },
        { buttonLabel: "8", value: "8" },
      ],
    },
  ],
  [
    {
      question: "What is this number?",
      phonetic: "10",
      correctAnswer: "ten",
      answers: [
        { buttonLabel: "namaya", value: "nine", sinhala: "නම‍ය" },
        { buttonLabel: "hata", value: "seven", sinhala: "හත" },
        { buttonLabel: "dahaya", value: "ten", sinhala: "දහ‍ය" },
        { buttonLabel: "aṭa", value: "eight", sinhala: "අට" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "දහ‍ය",
      correctAnswer: "10",
      answers: [
        { buttonLabel: "9", value: "9" },
        { buttonLabel: "7", value: "7" },
        { buttonLabel: "10", value: "10" },
        { buttonLabel: "8", value: "8" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "එකොළහ",
      correctAnswer: "11",
      answers: [
        { buttonLabel: "11", value: "11" },
        { buttonLabel: "15", value: "15" },
        { buttonLabel: "13", value: "13" },
        { buttonLabel: "16", value: "16" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "11",
      correctAnswer: "eleven",
      answers: [
        { buttonLabel: "ekoḷaha", value: "eleven", sinhala: "එකොළහ" },
        { buttonLabel: "pahaḷova", value: "fifteen", sinhala: "පහළොව" },
        { buttonLabel: "dahatuna", value: "thirteen", sinhala: "දහතුන" },
        { buttonLabel: "dāsaya", value: "sixteen", sinhala: "දාසය" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "දොළහ",
      correctAnswer: "12",
      answers: [
        { buttonLabel: "12", value: "12" },
        { buttonLabel: "18", value: "18" },
        { buttonLabel: "14", value: "14" },
        { buttonLabel: "20", value: "20" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "12",
      correctAnswer: "twelve",
      answers: [
        { buttonLabel: "doḷaha", value: "twelve", sinhala: "දොළහ" },
        { buttonLabel: "dahaaṭa", value: "eighteen", sinhala: "දහඅට" },
        { buttonLabel: "dāhatara", value: "fourteen", sinhala: "දාහතර" },
        { buttonLabel: "vissa", value: "twenty", sinhala: "විස්ස" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "දහතුන",
      correctAnswer: "13",
      answers: [
        { buttonLabel: "13", value: "13" },
        { buttonLabel: "17", value: "17" },
        { buttonLabel: "19", value: "19" },
        { buttonLabel: "11", value: "11" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "13",
      correctAnswer: "thirteen",
      answers: [
        { buttonLabel: "dahatuna", value: "thirteen", sinhala: "දහතුන" },
        { buttonLabel: "dāhata", value: "seventeen", sinhala: "දාහත" },
        { buttonLabel: "dahanamaya", value: "nineteen", sinhala: "දහනමය" },
        { buttonLabel: "ekoḷaha", value: "eleven", sinhala: "එකොළහ" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "දාහතර",
      correctAnswer: "14",
      answers: [
        { buttonLabel: "14", value: "14" },
        { buttonLabel: "20", value: "20" },
        { buttonLabel: "12", value: "12" },
        { buttonLabel: "16", value: "16" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "14",
      correctAnswer: "fourteen",
      answers: [
        { buttonLabel: "dāhatara", value: "fourteen", sinhala: "දාහතර" },
        { buttonLabel: "vissa", value: "twenty", sinhala: "විස්ස" },
        { buttonLabel: "doḷaha", value: "twelve", sinhala: "දොළහ" },
        { buttonLabel: "dāsaya", value: "sixteen", sinhala: "දාසය" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "පහළොව",
      correctAnswer: "15",
      answers: [
        { buttonLabel: "15", value: "15" },
        { buttonLabel: "19", value: "19" },
        { buttonLabel: "13", value: "13" },
        { buttonLabel: "17", value: "17" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "15",
      correctAnswer: "fifteen",
      answers: [
        { buttonLabel: "pahaḷova", value: "fifteen", sinhala: "පහළොව" },
        { buttonLabel: "dahanamaya", value: "nineteen", sinhala: "දහනමය" },
        { buttonLabel: "dahatuna", value: "thirteen", sinhala: "දහතුන" },
        { buttonLabel: "dāhata", value: "seventeen", sinhala: "දාහත" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "දාසය",
      correctAnswer: "16",
      answers: [
        { buttonLabel: "16", value: "16" },
        { buttonLabel: "18", value: "18" },
        { buttonLabel: "12", value: "12" },
        { buttonLabel: "14", value: "14" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "16",
      correctAnswer: "sixteen",
      answers: [
        { buttonLabel: "dāsaya", value: "sixteen", sinhala: "දාසය" },
        { buttonLabel: "dahaaṭa", value: "eighteen", sinhala: "දහඅට" },
        { buttonLabel: "doḷaha", value: "twelve", sinhala: "දොළහ" },
        { buttonLabel: "dāhatara", value: "fourteen", sinhala: "දාහතර" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "දාහත",
      correctAnswer: "17",
      answers: [
        { buttonLabel: "17", value: "17" },
        { buttonLabel: "15", value: "15" },
        { buttonLabel: "19", value: "19" },
        { buttonLabel: "13", value: "13" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "17",
      correctAnswer: "seventeen",
      answers: [
        { buttonLabel: "dāhata", value: "seventeen", sinhala: "දාහත" },
        { buttonLabel: "pahaḷova", value: "fifteen", sinhala: "පහළොව" },
        { buttonLabel: "dahanamaya", value: "nineteen", sinhala: "දහනමය" },
        { buttonLabel: "dahatuna", value: "thirteen", sinhala: "දහතුන" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "දහඅට",
      correctAnswer: "18",
      answers: [
        { buttonLabel: "18", value: "18" },
        { buttonLabel: "14", value: "14" },
        { buttonLabel: "12", value: "12" },
        { buttonLabel: "16", value: "16" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "18",
      correctAnswer: "eighteen",
      answers: [
        { buttonLabel: "dahaaṭa", value: "eighteen", sinhala: "දහඅට" },
        { buttonLabel: "dāhatara", value: "fourteen", sinhala: "දාහතර" },
        { buttonLabel: "doḷaha", value: "twelve", sinhala: "දොළහ" },
        { buttonLabel: "dāsaya", value: "sixteen", sinhala: "දාසය" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "දහනමය",
      correctAnswer: "19",
      answers: [
        { buttonLabel: "19", value: "19" },
        { buttonLabel: "17", value: "17" },
        { buttonLabel: "15", value: "15" },
        { buttonLabel: "13", value: "13" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "19",
      correctAnswer: "nineteen",
      answers: [
        { buttonLabel: "dahanamaya", value: "nineteen", sinhala: "දහනමය" },
        { buttonLabel: "dāhata", value: "seventeen", sinhala: "දාහත" },
        { buttonLabel: "pahaḷova", value: "fifteen", sinhala: "පහළොව" },
        { buttonLabel: "dahatuna", value: "thirteen", sinhala: "දහතුන" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "විස්ස",
      correctAnswer: "20",
      answers: [
        { buttonLabel: "20", value: "20" },
        { buttonLabel: "12", value: "12" },
        { buttonLabel: "18", value: "18" },
        { buttonLabel: "16", value: "16" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "20",
      correctAnswer: "twenty",
      answers: [
        { buttonLabel: "vissa", value: "twenty", sinhala: "විස්ස" },
        { buttonLabel: "doḷaha", value: "twelve", sinhala: "දොළහ" },
        { buttonLabel: "dahaaṭa", value: "eighteen", sinhala: "දහඅට" },
        { buttonLabel: "dāsaya", value: "sixteen", sinhala: "දාසය" },
      ],
    },
  ],
  [
    {
      question: "What is this number?",
      phonetic: "විස්ස",
      correctAnswer: "20",
      answers: [
        { buttonLabel: "20", value: "20" },
        { buttonLabel: "12", value: "12" },
        { buttonLabel: "18", value: "18" },
        { buttonLabel: "16", value: "16" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "20",
      correctAnswer: "twenty",
      answers: [
        { buttonLabel: "vissa", value: "twenty", sinhala: "විස්ස" },
        { buttonLabel: "doḷaha", value: "twelve", sinhala: "දොළහ" },
        { buttonLabel: "dahaaṭa", value: "eighteen", sinhala: "දහඅට" },
        { buttonLabel: "dāsaya", value: "sixteen", sinhala: "දාසය" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "විසි එක",
      correctAnswer: "21",
      answers: [
        { buttonLabel: "21", value: "21" },
        { buttonLabel: "25", value: "25" },
        { buttonLabel: "23", value: "23" },
        { buttonLabel: "26", value: "26" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "21",
      correctAnswer: "twenty-one",
      answers: [
        { buttonLabel: "visi eka", value: "twenty-one", sinhala: "විසි එක" },
        { buttonLabel: "visi paha", value: "twenty-five", sinhala: "විසි පහ" },
        {
          buttonLabel: "visi tuna",
          value: "twenty-three",
          sinhala: "විසි තුන",
        },
        { buttonLabel: "visi haya", value: "twenty-six", sinhala: "විසි හය" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "විසි දෙක",
      correctAnswer: "22",
      answers: [
        { buttonLabel: "22", value: "22" },
        { buttonLabel: "28", value: "28" },
        { buttonLabel: "24", value: "24" },
        { buttonLabel: "30", value: "30" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "22",
      correctAnswer: "twenty-two",
      answers: [
        { buttonLabel: "visi deka", value: "twenty-two", sinhala: "විසි දෙක" },
        { buttonLabel: "visi aṭa", value: "twenty-eight", sinhala: "විසි අට" },
        {
          buttonLabel: "visi hatara",
          value: "twenty-four",
          sinhala: "විසි හතර",
        },
        { buttonLabel: "tiha", value: "thirty", sinhala: "තිහ" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "විසි තුන",
      correctAnswer: "23",
      answers: [
        { buttonLabel: "23", value: "23" },
        { buttonLabel: "27", value: "27" },
        { buttonLabel: "29", value: "29" },
        { buttonLabel: "21", value: "21" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "23",
      correctAnswer: "twenty-three",
      answers: [
        {
          buttonLabel: "visi tuna",
          value: "twenty-three",
          sinhala: "විසි තුන",
        },
        { buttonLabel: "visi hata", value: "twenty-seven", sinhala: "විසි හත" },
        {
          buttonLabel: "visi namaya",
          value: "twenty-nine",
          sinhala: "විසි නමය",
        },
        { buttonLabel: "visi eka", value: "twenty-one", sinhala: "විසි එක" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "විසි හතර",
      correctAnswer: "24",
      answers: [
        { buttonLabel: "24", value: "24" },
        { buttonLabel: "30", value: "30" },
        { buttonLabel: "22", value: "22" },
        { buttonLabel: "26", value: "26" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "24",
      correctAnswer: "twenty-four",
      answers: [
        {
          buttonLabel: "visi hatara",
          value: "twenty-four",
          sinhala: "විසි හතර",
        },
        { buttonLabel: "tiha", value: "thirty", sinhala: "තිහ" },
        { buttonLabel: "visi deka", value: "twenty-two", sinhala: "විසි දෙක" },
        { buttonLabel: "visi haya", value: "twenty-six", sinhala: "විසි හය" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "විසි පහ",
      correctAnswer: "25",
      answers: [
        { buttonLabel: "25", value: "25" },
        { buttonLabel: "29", value: "29" },
        { buttonLabel: "23", value: "23" },
        { buttonLabel: "27", value: "27" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "25",
      correctAnswer: "twenty-five",
      answers: [
        { buttonLabel: "visi paha", value: "twenty-five", sinhala: "විසි පහ" },
        {
          buttonLabel: "visi namaya",
          value: "twenty-nine",
          sinhala: "විසි නමය",
        },
        {
          buttonLabel: "visi tuna",
          value: "twenty-three",
          sinhala: "විසි තුන",
        },
        { buttonLabel: "visi hata", value: "twenty-seven", sinhala: "විසි හත" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "විසි හය",
      correctAnswer: "26",
      answers: [
        { buttonLabel: "26", value: "26" },
        { buttonLabel: "28", value: "28" },
        { buttonLabel: "22", value: "22" },
        { buttonLabel: "24", value: "24" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "26",
      correctAnswer: "twenty-six",
      answers: [
        { buttonLabel: "visi haya", value: "twenty-six", sinhala: "විසි හය" },
        { buttonLabel: "visi aṭa", value: "twenty-eight", sinhala: "විසි අට" },
        { buttonLabel: "visi deka", value: "twenty-two", sinhala: "විසි දෙක" },
        {
          buttonLabel: "visi hatara",
          value: "twenty-four",
          sinhala: "විසි හතර",
        },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "විසි හත",
      correctAnswer: "27",
      answers: [
        { buttonLabel: "27", value: "27" },
        { buttonLabel: "25", value: "25" },
        { buttonLabel: "29", value: "29" },
        { buttonLabel: "23", value: "23" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "27",
      correctAnswer: "twenty-seven",
      answers: [
        { buttonLabel: "visi hata", value: "twenty-seven", sinhala: "විසි හත" },
        { buttonLabel: "visi paha", value: "twenty-five", sinhala: "විසි පහ" },
        {
          buttonLabel: "visi namaya",
          value: "twenty-nine",
          sinhala: "විසි නමය",
        },
        {
          buttonLabel: "visi tuna",
          value: "twenty-three",
          sinhala: "විසි තුන",
        },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "විසි අට",
      correctAnswer: "28",
      answers: [
        { buttonLabel: "28", value: "28" },
        { buttonLabel: "24", value: "24" },
        { buttonLabel: "22", value: "22" },
        { buttonLabel: "26", value: "26" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "28",
      correctAnswer: "twenty-eight",
      answers: [
        { buttonLabel: "visi aṭa", value: "twenty-eight", sinhala: "විසි අට" },
        {
          buttonLabel: "visi hatara",
          value: "twenty-four",
          sinhala: "විසි හතර",
        },
        { buttonLabel: "visi deka", value: "twenty-two", sinhala: "විසි දෙක" },
        { buttonLabel: "visi haya", value: "twenty-six", sinhala: "විසි හය" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "විසි නමය",
      correctAnswer: "29",
      answers: [
        { buttonLabel: "29", value: "29" },
        { buttonLabel: "27", value: "27" },
        { buttonLabel: "25", value: "25" },
        { buttonLabel: "23", value: "23" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "29",
      correctAnswer: "twenty-nine",
      answers: [
        {
          buttonLabel: "visi namaya",
          value: "twenty-nine",
          sinhala: "විසි නමය",
        },
        { buttonLabel: "visi hata", value: "twenty-seven", sinhala: "විසි හත" },
        { buttonLabel: "visi paha", value: "twenty-five", sinhala: "විසි පහ" },
        {
          buttonLabel: "visi tuna",
          value: "twenty-three",
          sinhala: "විසි තුන",
        },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "තිහ",
      correctAnswer: "30",
      answers: [
        { buttonLabel: "30", value: "30" },
        { buttonLabel: "22", value: "22" },
        { buttonLabel: "28", value: "28" },
        { buttonLabel: "26", value: "26" },
      ],
    },
    {
      question: "What is this number?",
      phonetic: "30",
      correctAnswer: "thirty",
      answers: [
        { buttonLabel: "tiha", value: "thirty", sinhala: "තිහ" },
        { buttonLabel: "visi deka", value: "twenty-two", sinhala: "විසි දෙක" },
        { buttonLabel: "visi aṭa", value: "twenty-eight", sinhala: "විසි අට" },
        { buttonLabel: "visi haya", value: "twenty-six", sinhala: "විසි හය" },
      ],
    },
  ],
];
