name: Daily Email Reminders

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight UTC every day
  workflow_dispatch: # Allows manual triggering

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call Next.js API with Authentication
        run: |
          curl -X POST "${{ secrets.API_URL }}/send-reminders" \
          -H "Authorization: Bearer ${{ secrets.ACTIONS_SECRET }}" \
          -w "\nHTTP Code: %{http_code}\n" -o response.txt
          cat response.txt
